title: XLcloud
email: jason@xlcloud.co.uk
description: >- # this means to ignore newlines until "baseurl:"
  We do stuff.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://xlcloud.co.uk" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: JasonGregson
github_username:  Gyja

# Build settings
theme: minima

exclude:
  - Gemfile
  - Gemfile.lock